Début du script
Bug lors de l'appel premier extracteur java html
Error: Could not find or load main class pdl.wiki.HTMLExtractor
Caused by: java.lang.ClassNotFoundException: pdl.wiki.HTMLExtractor